### ISSUE TITLE
Sitemaps not working 1.9+

### ISSUE THREAD

**Issue by donaldboulton** [OrchardCMS/Orchard#6372]
Sitemaps do not work with orchard caching.
All sitemap modules do not work with 1.9+.

How can we add one at the root without it being compressed.
Or is there some way in the web.config to tell Orchard and IIS not to cache .xml

**Comment by sebastienros** [comment]
What is the issue?

Are there two issues here? If so please open another one.

**Comment by sebastienros** [comment]
Are you talking about his one? https://github.com/webadvanced/Orchard-SiteMap

Then is it a compilation error?

**Comment by donaldboulton** [comment]
Just hard coded one at root and change web config.

adding under sys web http handlers under clear `<add verb="*" path="sitemap.xml" type="System.Web.StaticFileHandler" />`

and under handlers add: `<add name="SitemapXmlFileHandler" path="*.xml" verb="*" modules="StaticFileModule" resourceType="File" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" requireAccess="Read"/> `

The modules are not building the sitemap correctly adding lastmod after priority starting. Url set is just that, `<urlset>`  = no schema info as = `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">`
But my problem initially was a cached xml file without the proper encoding, so I told IIS not to cache it, as : under caching - profiles add: `<add extension=".xml" policy="DisableCache" kernelCachePolicy="DisableCache>
Works fine now!
And yes I had been using Web Advanced site map as you asked = does not work for 1.9+ and unless you fixed references to jQuaryUI it would not let you sort, so that module needs alot of work, no sitemap modules work with 1.9+.
