### ISSUE TITLE
Problem installing node modules 

### ISSUE THREAD

**Issue by mehranrezaei** [OrchardCMS/Orchard#8522]
@sebastienros 
@chanondw 
@rtpHarry 
@gtandeciarz 

I did the following steps:

```
D:\>git clone https://github.com/OrchardCMS/Orchard.git
Cloning into 'Orchard'...
remote: Enumerating objects: 194040, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 194040 (delta 0), reused 0 (delta 0), pack-reused 194039
Receiving objects: 100% (194040/194040), 192.92 MiB | 657.00 KiB/s, done.
Resolving deltas: 100% (143929/143929), done.
Updating files: 100% (7476/7476), done.
```
Then I went to the source folder and tried to install node modules , but I get thousands of errors :
```
D:\Orchard\src>npm install
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated har-validator@4.2.1: this library is no longer supported
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated svgo@0.7.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated request@2.81.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated browserslist@1.5.2: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated gulp-header@1.8.8: Removed event-stream from gulp-header
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm notice
npm notice New minor version of npm available! 8.1.2 -> 8.3.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.3.0
npm notice Run npm install -g npm@8.3.0 to update!
npm notice
npm ERR! code 1
npm ERR! path D:\Orchard\src\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe D:\Orchard\src\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'D:\\Orchard\\src\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.1 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\Orchard\src\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\Orchard\src\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\Orchard\src\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\Orchard\src\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\Orchard\src\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\Orchard\src\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\Orchard\src\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\Orchard\src\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\Orchard\src\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\Orchard\src\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\Orchard\src\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\Orchard\src\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\Orchard\src\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\Orchard\src\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\Orchard\src\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\Orchard\src\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\Orchard\src\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\Orchard\src\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\Orchard\src\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\Orchard\src\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\Orchard\src\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\Orchard\src\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\Orchard\src\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\Orchard\src\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "python". checking python launcher
npm ERR! gyp verb could not find "python". guessing location
npm ERR! gyp verb ensuring that file exists: C:\Python27\python.exe
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (D:\Orchard\src\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (D:\Orchard\src\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at callback (D:\Orchard\src\node_modules\graceful-fs\polyfills.js:299:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Orchard\\src\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd D:\Orchard\src\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Arman\AppData\Local\npm-cache\_logs\2021-12-21T07_11_01_283Z-debug.log
```

I read hundreds of pages in GitHub and SO and tried all the solutions so that I could finally see the Gulp tasks in the Task Runner Explorer section. 

But now when I change a Assets file, I get a hundred more errors!
```
D:\Orchard\src> cmd.exe /c gulp -b "D:\Orchard\src" --color --gulpfile "D:/Dena/src/Gulpfile.js" watch
[11:25:25] Using gulpfile D:\Orchard\src\Gulpfile.js
[11:25:25] Starting 'watch'...
[11:25:32] Starting '<anonymous>'...
Asset manifest file 'undefined' was undefined, restarting watcher.
[11:25:32] '<anonymous>' errored after 916 μs
[11:25:32] TypeError: inputWatcher.remove is not a function
    at D:\Orchard\src\Gulpfile.js:72:26
    at bound (domain.js:427:14)
    at runBound (domain.js:440:12)
    at asyncRunner (D:\Orchard\src\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)
[11:25:32] Starting '<anonymous>'...
Asset manifest file 'undefined' was undefined, restarting watcher.
[11:25:32] '<anonymous>' errored after 243 μs
[11:25:32] TypeError: inputWatcher.remove is not a function
    at D:\Orchard\src\Gulpfile.js:72:26
    at bound (domain.js:427:14)
    at runBound (domain.js:440:12)
    at asyncRunner (D:\Orchard\src\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)
[11:25:32] Starting '<anonymous>'...
Asset manifest file 'undefined' was undefined, restarting watcher.
[11:25:32] '<anonymous>' errored after 199 μs
[11:25:32] TypeError: inputWatcher.remove is not a function
    at D:\Orchard\src\Gulpfile.js:72:26
    at bound (domain.js:427:14)
    at runBound (domain.js:440:12)
    at asyncRunner (D:\Orchard\src\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

```

There has always been a problem with Gulp, and I have seen that others have the same problem. I think manual installation of dependencies is much easier than this method!!!
I spent two days on this problem but still could not run a simple bundle system!!!

**Comment by Skrypt** [comment]
We use the LTS version of Node.js installer to compile our assets with the npm version packaged with it. Not sure if this will work with the latest version if that's what you are using.

**Comment by Skrypt** [comment]
I just looked and I'm using npm 8.1.3

**Comment by Skrypt** [comment]
stack Error: Can't find Python executable "python"

That seems to be your issue. Install "Python" and it should remove that main issue. Other issues are "deprecated" assets that should be upgraded if we can; unless it breaks our integrations.

**Comment by mehranrezaei** [comment]
> Skrypt

I use node v16.13.1 LTS and NPM v8.1.2

**Comment by mehranrezaei** [comment]
@Skrypt 

As I mentioned above, I was finally able to install node modules, but when I run it in Task Runner, I get the following error :
```
D:\Orchard\src> cmd.exe /c gulp -b "D:\Orchard\src" --color --gulpfile "D:/Dena/src/Gulpfile.js" watch
[11:25:25] Using gulpfile D:\Orchard\src\Gulpfile.js
[11:25:25] Starting 'watch'...
[11:25:32] Starting '<anonymous>'...
Asset manifest file 'undefined' was undefined, restarting watcher.
[11:25:32] '<anonymous>' errored after 916 μs
[11:25:32] TypeError: inputWatcher.remove is not a function
    at D:\Orchard\src\Gulpfile.js:72:26
    
    ....
    
```

**Comment by Skrypt** [comment]
The gulp pipeline in Orchard has not been updated for years that might be the issue. You are trying to build it with a newer version of npm and I don't remember what we were using at that time.

**Comment by mehranrezaei** [comment]
@Skrypt 

Can you guide me how to update the gulpfile.js? What happens if I change all the versions in this file to the latest version?

**Comment by Skrypt** [comment]
It's probably not a good idea since everything is dependent on the versions fixed in the package.json files. You will need to install older versions of Node.js and figure out which one works.

**Comment by 0liver** [comment]
Although many thinks in the Gulp pipeline still work in newer Node.js versions, the truth is that Gulp 4 does not officially support even Node.js 14: https://github.com/gulpjs/gulp/discussions/2649.

The breaking watch task in Gulp after upgrading to Node.js 16 actually led us to dropping Gulp altogether.

**Comment by BenedekFarkas** [comment]
Works with Node 7 on both `1.10.x` and `dev`. I recommend using [NVM](https://github.com/coreybutler/nvm-windows) for development.
