### ISSUE TITLE
Routes not working in a fresh module with 1.5.1

### ISSUE THREAD

**Issue by orchardbot** [OrchardCMS/Orchard#2883]
__brcarey__ created:
https://orchard.codeplex.com/workitem/19056

- Create a fresh instance with the Orchard.Web.1.5.1.zip binary install
- Codegen a new module
- Create a controller action that returns a simple view
- Create a route that makes that controller action the home page (url = "") and with priority >= 81
- Visit home page and receive 404 (controller not found at "/" or does not implement IController)

If I cut over to the latest changeset on 1.x the same module works fine. Am I doing something wrong?
